services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    env_file:
      - .env
    volumes:
      - ./uptime-kuma-data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(${URL_FOR_TRAEFIK})
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.routers.uptime-kuma.tls.certresolver=leresolver
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
      - traefik.docker.network=proxy
    networks:
      - proxy

networks:
  proxy:
    external: true